version: '3'
services:
  config:
    image: config-service
    ports:
      - 8090:8090
    extends:
      file: docker-compose-common.yml
      service: common
  gateway:
    image: gateway-service
    extends:
      file: docker-compose-common.yml
      service: common
    ports:
      - 80:8080
  discovery:
    image: discovery-service
    extends:
      file: docker-compose-common.yml
      service: common
    ports:
      - 8761:8761
  user-service:
    image: user-service
    ports:
      - 8081:8081
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      DATABASE_HOST: user-db
      KEYCLOAK_SERVER: keycloak
      KEYCLOAK_PORT: 8080
  movie-service:
    image: movie-service
    ports:
      - 8082:8082
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      DATABASE_HOST: movie-db
  tvshow-service:
    image: tvshow-service
    ports:
      - 8083:8083
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      DATABASE_HOST: tvshow-db
  comment-service:
    image: comment-service
    ports:
      - 8084:8084
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      DATABASE_HOST: comment-db
  rating-service:
    image: rating-service
    ports:
      - 8085:8085
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      DATABASE_HOST: rating-db
  tvshow-db:
    image: postgres
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      POSTGRES_PASSWORD: postgres
  movie-db:
    image: postgres
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      POSTGRES_PASSWORD: postgres
  comment-db:
    image: postgres
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      POSTGRES_PASSWORD: postgres
  rating-db:
    image: postgres
    ports:
      - 5432:5432
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      POSTGRES_PASSWORD: postgres
  keycloak:
    image: wizzn/keycloak:14
    extends:
      file: docker-compose-common.yml
      service: common
    command:
      - "-b 0.0.0.0 -Djboss.bind.address.private=127.0.0.1 -Djboss.bind.address=0.0.0.0 -Djgroups.bind_addr=127.0.0.1 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    volumes:
      - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
      - 9990:9990
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/" ]
      interval: 1s
      timeout: 3s
      retries: 30
  keycloak-db:
    image: postgres
    extends:
      file: docker-compose-common.yml
      service: common
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  zipkin:
    image: openzipkin/zipkin
    extends:
      file: docker-compose-common.yml
      service: common
    ports:
      - 9411:9411
  rabbitmq:
    platform: linux/amd64
    image: rabbitmq:3-management
    extends:
      file: docker-compose-common.yml
      service: common
    ports:
      - 5672:5672
      - 5673:15672
  kafka:
    image: confluentinc/cp-kafka:5.5.8
    ports:
      - 9092:9092
    extends:
      file: docker-compose-common.yml
      service: common
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.8
    extends:
      file: docker-compose-common.yml
      service: common
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    extends:
      file: docker-compose-common.yml
      service: common
    ports:
      - 8089:8080
