version: '3.8'

services:
  config:
    extends:
      file: docker-compose-base.yml
      service: config
  gateway:
    extends:
      file: docker-compose-base.yml
      service: gateway
  discovery:
    extends:
      file: docker-compose-base.yml
      service: discovery
  user-service:
    extends:
      file: docker-compose-base.yml
      service: user-service
  movie-service:
    extends:
      file: docker-compose-base.yml
      service: movie-service
    depends_on:
      - movie-db
  movie-db:
    extends:
      file: docker-compose-base.yml
      service: movie-db
  tvshow-service:
    extends:
      file: docker-compose-base.yml
      service: tvshow-service
    depends_on:
      - tvshow-db
  tvshow-db:
    extends:
      file: docker-compose-base.yml
      service: tvshow-db
  comment-service:
    extends:
      file: docker-compose-base.yml
      service: comment-service
    depends_on:
      - comment-db
  comment-db:
    extends:
      file: docker-compose-base.yml
      service: comment-db
  rating-service:
    extends:
      file: docker-compose-base.yml
      service: rating-service
    depends_on:
      - rating-db
  rating-db:
    extends:
      file: docker-compose-base.yml
      service: rating-db
  keycloak:
    extends:
      file: docker-compose-base.yml
      service: keycloak
    depends_on:
      - keycloak-db
  keycloak-db:
    extends:
      file: docker-compose-base.yml
      service: keycloak-db
  zipkin:
    extends:
      file: docker-compose-base.yml
      service: zipkin
  rabbitmq:
    extends:
      file: docker-compose-base.yml
      service: rabbitmq
  kafka:
    platform: linux/amd64
    extends:
      file: docker-compose-base.yml
      service: kafka
    depends_on:
      - zookeeper
  zookeeper:
    platform: linux/amd64
    extends:
      file: docker-compose-base.yml
      service: zookeeper
  kafka-ui:
    platform: linux/amd64
    extends:
      file: docker-compose-base.yml
      service: kafka-ui
    depends_on:
      - zookeeper
      - kafka

networks:
  all:
    driver: bridge
