spring:
  application:
    name: user-service
  zipkin:
    base-url: http://${ZIPKIN_SERVER:localhost}:${ZIPKIN_PORT:9411}

server:
  port: 8081

keycloak:
  enabled: true
  realm: spring-realm
  auth-server-url: http://${KEYCLOAK_SERVER:localhost}:8080/auth
  public-client: true
  bearer-only: true
  credentials:
    secret: bbc02d7c-d18e-4fb7-8882-23165e849810
  ssl-required: none
  resource: web-app
  use-resource-role-mappings: true
