server:
  port: 8082
spring:
  config:
    import: optional:configserver:http://localhost:8090/
  application:
    name: movie-service
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:55000/movie-service
    username: postgres
    password: postgrespw
  # JPA properties
  jpa:
    properties:      
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true    
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # open-in-view: false
    # generate-ddl: true
  sql:
    init:
      mode: always
  zipkin:
    base-url: http://${ZIPKIN_SERVER:localhost}:9411
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}    
    consumer:      
      group-id: group-1
      auto-offset-reset: latest      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always